[tool.black]
check = "true"
include = """
src\/.*\.pyi?$|
ports\/.*\.pyi?$
"""
exclude = """
src\/packages\/microdot\/.*\.pyi?$|
ports\/esp32\/third-party\/.*\.pyi?$|
third-party\/.*\.pyi?$|
bin\/.*\.pyi?$
"""
