PROG ?= $(BUILD)/micropython-dev

FROZEN_MANIFEST ?= $(VARIANT_DIR)/manifest.py

MICROPY_ROM_TEXT_COMPRESSION = 1
MICROPY_VFS_FAT = 1
MICROPY_VFS_LFS1 = 1
MICROPY_VFS_LFS2 = 1

MICROPY_PY_BLUETOOTH ?= 1

# specify c modules
CITY_SKIES_ROOT = $(VARIANT_DIR)/../../../..
USER_C_MODULES = $(CITY_SKIES_ROOT)/src/cmodules
