# continuous deployment
name: cd

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:

  # build esp32
  build-esp32:
    name: build esp32 targets
    uses: ./.github/workflows/build-esp32.yml

  # publish the binaries to the release
  publish:
    runs-on: [self-hosted]
    needs: [build-esp32]
    steps:
      # create binaries
      # (must run on same runner as build-esp32 and dist is expected to exist)
      - name: create distribution binaries
        run: |
          tar -czvf ports/esp32/dist.tar.gz ports/esp32/dist
          zip -r ports/esp32/dist.zip ports/esp32/dist

      # attach binaries to release
      - name: publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          file: ports/esp32/dist.tar.gz

      - name: publish binaries
        uses: svenstaro/upload-release-action@v2
        with:
          file: ports/esp32/dist.zip
