# continuous integration
name: ci

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint:
    name: 'linting'
    uses: ./.github/workflows/lint.yml

  build-esp32:
    # build esp32 targets
    name: build esp32 targets
    uses: ./.github/workflows/build-esp32.yml

  build-unix:
    # build unix variants
    name: build unix variants
    uses: ./.github/workflows/build-unix.yml
